name: gnb
channels: !!python/tuple
- !!python/unicode 'defaults'
dependencies:
- certifi=2016.2.28=py27_0
- openssl=1.0.2l=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=36.4.0=py27_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - numpy==1.14.0
